// 武器
ServerEvents.tags('item', event => {
    event.add("ga:weapon/melee",
        [
            "mutantmonsters:creeper_shard",
            "irons_spellbooks:graybeard_staff",
            "minecraft:wooden_sword",
            "minecraft:golden_sword",
            "cataclysm_spellbooks:bloom_stone_staff",
            "cataclysm_spellbooks:coral_staff",
            "cataclysm_spellbooks:fake_wudjets_staff",
            "cataclysm_spellbooks:void_staff",
            "cataclysm_spellbooks:spirit_sunderer",
            "cataclysm_spellbooks:soul_brazier",
            "hyrule_terrors:bokoblin_arm",
            "codex_of_champions:nameless_staff",
            "hazennstuff:frieren_staff",
            "hazennstuff:wisewood_cane",
            "hazennstuff:rod_of_discord",
            "irons_spellbooks:artificer_cane",
            "minecraft:stone_sword",
            "mowziesmobs:spear",
            "cataclysm:athame",
            "hyrule_terrors:lizalfos_horn_dagger",
            "irons_spellbooks:ice_staff",
            "irons_spellbooks:lightning_rod",
            "minecraft:iron_sword",
            "minecraft:mace",
            "mutantmonsters:endersoul_hand",
            "cataclysm:khopesh",
            "cataclysm:black_steel_sword",
            "tide:blazing_swordfish",
            "endermanoverhaul:corrupted_blade",
            "cataclysm:coral_spear",
            "minecraft:wooden_axe",
            "minecraft:golden_axe",
            "minecraft:diamond_sword",
            "crystal_chronicles:staff",
            "illagerinvasion:platinum_infused_hatchet",
            "codex_of_champions:brutis",
            "codex_of_champions:sculk_slicer",
            "hazennstuff:spectral_pickaxe",
            "irons_spellbooks:magehunter",
            "cataclysm:the_annihilator",
            "cataclysm:the_immolator",
            "minecraft:netherite_sword",
            "alshanex_familiars:bard_harp",
            "crystal_chronicles:chakram",
            "cataclysm:tidal_claws",
            "hyrule_terrors:silver_longsword",
            "codex_of_champions:excalibur",
            "hazennstuff:beongae",
            "irons_spellbooks:blood_staff",
            "irons_spellbooks:amethyst_rapier",
            "irons_spellbooks:misery",
            "cataclysm:meat_shredder",
            "minecraft:stone_axe",
            "minecraft:iron_axe",
            "minecraft:diamond_axe",
            "minecraft:trident",
            "mutantmonsters:hulk_hammer",
            "crystal_chronicles:paladin_sword",
            "crystal_chronicles:evocation_twinblade",
            "cataclysm:black_steel_axe",
            "codex_of_champions:angelic_annhilator",
            "hazennstuff:fireblossom_rapier",
            "bosses_of_mass_destruction:earthdive_spear",
            "irons_spellbooks:pyrium_staff",
            "cataclysm:ancient_spear",
            "minecraft:netherite_axe",
            "crystal_chronicles:spear",
            "crystal_chronicles:blood_scythe",
            "crystal_chronicles:lightning_bident",
            "cataclysm:coral_bardiche",
            "codex_of_champions:monosword",
            "codex_of_champions:plasmasword",
            "codex_of_champions:tri_blade",
            "hazennstuff:ancient_warriors_axe",
            "hazennstuff:skyscorcher",
            "hazennstuff:starfury",
            "irons_spellbooks:spellbreaker",
            "irons_spellbooks:claymore",
            "cataclysm:astrape",
            "cataclysm_spellbooks:monstrous_flamberge",
            "mowziesmobs:wrought_axe",
            "cataclysm:gauntlet_of_guard",
            "cataclysm:gauntlet_of_bulwark",
            "cataclysm:gauntlet_of_maelstrom",
            "codex_of_champions:soulfire_greatsword",
            "codex_of_champions:thunderbringer",
            "hazennstuff:ice_pike",
            "irons_spellbooks:keeper_flamberge",
            "irons_spellbooks:legionnaire_flamberge",
            "irons_spellbooks:decrepit_scythe",
            "crystal_chronicles:ice_hammer",
            "codex_of_champions:deathfire_greatsword",
            "remnant_bosses:ossukage_sword",
            "cataclysm:void_forge",
            "cataclysm:infernal_forge",
            "hyrule_terrors:knights_claymore",
            "codex_of_champions:crystal_claymore",
            "codex_of_champions:worldbreaker",
            "irons_spellbooks:hellrazor",
            "cataclysm:the_incinerator",
            "hyrule_terrors:boulder_breaker",
            "hazennstuff:bountiful_harvest",
            "cataclysm_spellbooks:hellfire_forge",
            "cataclysm:soul_render",
            "cataclysm:ceraunus",
            "irons_spellbooks:boreal_blade",
    ])
})

// 装备
ServerEvents.tags('item', event => {
    event.add("ga:armor",
        [
            "cataclysm:bone_reptile_helmet",
            "cataclysm:bone_reptile_chestplate",
            "cataclysm:ignitium_helmet",
            "cataclysm:ignitium_elytra_chestplate",
            "cataclysm:ignitium_chestplate",
            "cataclysm:ignitium_leggings",
            "cataclysm:ignitium_boots",
            "cataclysm:cursium_helmet",
            "cataclysm:cursium_chestplate",
            "cataclysm:cursium_leggings",
            "cataclysm:cursium_boots",
            "cataclysm:monstrous_helm",
            "cataclysm:bloom_stone_pauldrons",
            "crystal_chronicles:electromancer_helmet",
            "crystal_chronicles:electromancer_chestplate",
            "crystal_chronicles:electromancer_leggings",
            "crystal_chronicles:electromancer_boots",
            "crystal_chronicles:evoker_helmet",
            "crystal_chronicles:evoker_chestplate",
            "crystal_chronicles:evoker_leggings",
            "crystal_chronicles:evoker_boots",
            "crystal_chronicles:paladin_helmet",
            "crystal_chronicles:paladin_chestplate",
            "crystal_chronicles:paladin_leggings",
            "crystal_chronicles:paladin_boots",
            "crystal_chronicles:tank_helmet",
            "crystal_chronicles:tank_chestplate",
            "crystal_chronicles:tank_leggings",
            "crystal_chronicles:tank_boots",
            "crystal_chronicles:mage_helmet",
            "crystal_chronicles:mage_chestplate",
            "crystal_chronicles:mage_leggings",
            "crystal_chronicles:mage_boots",
            "crystal_chronicles:rogue_helmet",
            "crystal_chronicles:rogue_chestplate",
            "crystal_chronicles:rogue_leggings",
            "crystal_chronicles:rogue_boots",
            "crystal_chronicles:pyromancer_helmet",
            "crystal_chronicles:pyromancer_chestplate",
            "crystal_chronicles:pyromancer_leggings",
            "crystal_chronicles:pyromancer_boots",
            "crystal_chronicles:toxic_helmet",
            "crystal_chronicles:toxic_chestplate",
            "crystal_chronicles:toxic_leggings",
            "crystal_chronicles:toxic_boots",
            "codex_of_champions:blood_soul_boots",
            "codex_of_champions:blood_soul_leggings",
            "codex_of_champions:blood_soul_robes",
            "codex_of_champions:blood_soul_mask",
            "cataclysm_spellbooks:ignis_helmet",
            "cataclysm_spellbooks:ignis_chestplate",
            "cataclysm_spellbooks:ignis_chestplate_elytra",
            "cataclysm_spellbooks:ignis_leggings",
            "cataclysm_spellbooks:ignis_boots",
            "cataclysm_spellbooks:abyssal_warlock_helmet",
            "cataclysm_spellbooks:abyssal_warlock_mask",
            "cataclysm_spellbooks:abyssal_warlock_chestplate",
            "cataclysm_spellbooks:abyssal_warlock_leggings",
            "cataclysm_spellbooks:abyssal_warlock_boots",
            "cataclysm_spellbooks:cursium_mage_circlet",
            "cataclysm_spellbooks:cursium_mage_chestplate",
            "cataclysm_spellbooks:cursium_mage_elytra",
            "cataclysm_spellbooks:cursium_mage_skirt",
            "cataclysm_spellbooks:cursium_mage_boots",
    ])
})

// 饰品标签-翅膀
ServerEvents.tags('item', event => {
    event.add("curios:wing",
        [
            "#icarus:wings",
    ])
})
// 饰品标签-手部
ServerEvents.tags('item', event => {
    event.add("curios:hands",
        [
            "block_factorys_bosses:sandworm_dart",
        ]
    )
})
// 饰品标签-腰带
ServerEvents.tags('item', event => {
    event.add("curios:belt",
        [
            "minecraft:lantern",
            "minecraft:soul_lantern",
        ]
    )
})


// 任务识别标签-森罗种子
ServerEvents.tags('item', event => {
    event.add("ga:kaleidoscope/seeds",
        [
            "kaleidoscope_cookery:wild_rice",
            "kaleidoscope_cookery:tomato_seed",
            "kaleidoscope_cookery:chili_seed",
            "kaleidoscope_cookery:lettuce_seed",
        ]
    )
})
// 任务识别标签-作物
ServerEvents.tags('item', event => {
    event.add("ga:minecraft/crops",
        [
            "minecraft:pumpkin",
            "minecraft:wheat",
            "minecraft:melon",
            "minecraft:beetroot",
            "minecraft:carrot",
            "minecraft:potato",
            "kaleidoscope_cookery:tomato",
            "kaleidoscope_cookery:red_chili",
            "kaleidoscope_cookery:green_chili",
            "kaleidoscope_cookery:lettuce",
            "",
        ]
    )
})
// 任务识别标签-原版种子
ServerEvents.tags('item', event => {
    event.add("ga:minecraft/seeds",
        [
            "minecraft:pumpkin_seeds",
            "minecraft:wheat_seeds",
            "minecraft:melon_seeds",
            "minecraft:beetroot_seeds",
            "minecraft:carrot",
            "minecraft:potato",
        ]
    )
})
// 任务识别标签-建筑魔杖
ServerEvents.tags('item', event => {
    event.add("ga:item/buildingwands",
        [
            "wands:stone_wand",
            "wands:golden_wand",
            "wands:diamond_wand",
            "wands:netherite_wand",
            "wands:creative_wand",
        ]
    )
})