[Server]
	#Swim speed multiplier
	# Default: 2.0
	# Range: 1.0 ~ 10.0
	swimSpeedMultiplier = 2.0
	#Water breathing
	waterBreathing = true
	#Night vision
	nightVision = true
	#Aqua affinity
	aquaAffinity = true
