[general]
	#Minimum delay (in ticks)
	# Default: 300
	# Range: 0 ~ 600
	minDelay = 300
	#Maximum delay (in ticks)
	# Default: 300
	# Range: 0 ~ 600
	maxDelay = 300
	#Print message when skipping
	printOnSkip = true
	#Enable debug logging (no GUI entry)
	debugLog = false
