#How often should Day Invasions occur.
# Default: 21
# Range: > 1
dayInvasionRarity = 21
#Determines if day invasions can be canceled.
cancelableDayInvasions = true
#How often should day invasions be canceled.
#NOTE: An invasion is canceled once in every 'value' fixed invasions.
#NOTE: If an invasion is set to be cancel on the same cycle as a hyper/nightmare invasion, it will not be cancled.
# Default: 84
# Range: > 1
dayCancelInvasionRarity = 84
#Max Day Invasions that can occur at once.
# Default: 3
# Range: > 1
maxDayInvasions = 3
#How many days should pass when the Day Invasion Tier increases.
# Default: 50
# Range: > 0
dayTierIncreaseDelay = 50
#How often should Night Invasions occur.
# Default: 3
# Range: > 1
nightInvasionRarity = 3
#Determines if night invasions can be canceled.
cancelableNightInvasions = true
#How often should night invasions be canceled.
#NOTE: An invasion is canceled once in every 'value' fixed invasions.
#NOTE: If an invasion is set to be cancel on the same cycle as a hyper/nightmare invasion, it will not be cancled.
# Default: 12
# Range: > 1
nightCancelInvasionRarity = 12
#Max Night Invasions that can occur at once.
# Default: 3
# Range: > 1
maxNightInvasions = 3
#How many days should pass when the Night Invasion Tier increases.
# Default: 30
# Range: > 0
nightTierIncreaseDelay = 30
#How often should Hyper Invasions occur.
#NOTE: Changes will only take effect after the next Hyper invasion occurs or a new world is started.
# Default: 12
# Range: > 1
hyperInvasionRarity = 12
#How often should Nightmare Invasions occur.
#NOTE: Changes will only take effect after the next Nightmare invasion occurs or a new world is started.
# Default: 5
# Range: > 1
nightmareInvasionRarity = 5
#Sets the light level to zero during invasions in this dimension.
#NOTE: Does not affect brightness.
zeroLightLevelDuringInvasions = false
