[Blacklist]
	#write the registry name of the entities
	banned = [
		"darkdoppelganger:dark_doppelganger",
		"choccos_mobs:duck",
		"choccos_mobs:flamingo",
		"choccos_mobs:lizard",
		"choccos_mobs:octopus",
		"choccos_mobs:penguin",
		"choccos_mobs:piranha",
		"choccos_mobs:raccoon",
		"choccos_mobs:red_panda",
		"choccos_mobs:shrimp",
		"choccos_mobs:turkey",
		"minecraft:armadillo",
		"minecraft:axolotl",
		"minecraft:bat",
		"minecraft:camel",
		"minecraft:cat",
		"minecraft:chicken",
		"minecraft:cod",
		"minecraft:cow",
		"minecraft:donkey",
		"minecraft:frog",
		"minecraft:glow_squid",
		"minecraft:horse",
		"minecraft:mooshroom",
		"minecraft:mule",
		"minecraft:ocelot",
		"minecraft:parrot",
		"minecraft:pig",
		"minecraft:pufferfish",
		"minecraft:rabbit",
		"minecraft:salmon",
		"minecraft:sheep",
		"minecraft:sniffer",
		"minecraft:squid",
		"minecraft:tadpole",
		"minecraft:tropical_fish",
		"minecraft:turtle",
		"minecraft:bee",
		"minecraft:dolphin",
		"minecraft:fox",
		"minecraft:goat",
		"minecraft:llama",
		"minecraft:panda",
		"minecraft:trader_llama",
		"minecraft:wandering_trader",
		"livingthings:crab",
		"livingthings:raccoon",
		"livingthings:giraffe",
		"livingthings:elephant",
		"livingthings:flamingo",
		"livingthings:koala",
		"livingthings:mantaray",
		"livingthings:monkey",
		"livingthings:ostrich",
		"livingthings:owl",
		"livingthings:peacock",
		"livingthings:penguin",
		"livingthings:seahorse",
		"livingthings:shroomie",
		"livingthings:snail",
		"mutantmonsters:creeper_minion",
		"alshanex_familiars:mage_pet",
		"alshanex_familiars:archmage_pet",
		"alshanex_familiars:summoner_pet",
		"alshanex_familiars:necromancer_pet",
		"alshanex_familiars:hunter_pet",
		"alshanex_familiars:druid_pet",
		"alshanex_familiars:illusionist_pet",
		"alshanex_familiars:scorcher_pet",
		"alshanex_familiars:cleric_pet",
		"alshanex_familiars:plague_pet",
		"alshanex_familiars:bard_pet",
		"alshanex_familiars:frostling_pet",
		"alshanex_familiars:summoned_shadow",
		"alshanex_familiars:blue_bird",
		"alshanex_familiars:angel",
		"alshanex_familiars:decoy",
		"alshanex_familiars:soul_entity",
		"touhou_little_maid:broom",
		"touhou_little_maid:chair",
		"touhou_little_maid:maid",
		"dummmmmmy:target_dummy",
		"gametechbcs_spellbooks:hard_dead_king",
		"irons_spellbooks:summoned_skeleton",
		"irons_spellbooks:summoned_vex",
		"irons_spellbooks:summoned_claymore",
		"irons_spellbooks:summoned_polar_bear",
		"irons_spellbooks:summoned_rapier",
		"irons_spellbooks:summoned_sword",
		"irons_spellbooks:summoned_zombie",
		"creaturecorner:pigeon",
		"creaturecorner:endove",
		"ribbits:ribbit",
		"tide:angelfish",
		"tide:barracuda",
		"tide:bass",
		"tide:bluegill",
		"tide:clayfish",
		"tide:guppy",
		"tide:mackerel",
		"tide:mint_carp",
		"tide:ocean_perch",
		"tide:pike",
		"tide:sailfish",
		"tide:trout",
		"tide:tuna",
		"tide:yellow_perch",
		"tide:catfish",
		"irons_spellbooks:firefly_swarm",
		"minecraft:villager",
		"mowziesmobs:ferrous_wroughtnaut",
		"mowziesmobs:umvuthi",
		"illagerinvasion:invoker",
		"mowziesmobs:frostmaw",
		"irons_spellbooks:dead_king_corpse",
		"irons_spellbooks:dead_king",
		"irons_spellbooks:fire_boss",
		"remnant_bosses:ossukage",
		"fdbosses:chesed_monolith",
		"fdbosses:chesed",
		"bosses_of_mass_destruction:lich",
		"bosses_of_mass_destruction:void_blossom",
		"bosses_of_mass_destruction:gauntlet",
		"bosses_of_mass_destruction:obsidilith",
		"cataclysm:netherite_monstrosity",
		"cataclysm:ignited_revenant",
		"cataclysm:the_prowler",
		"cataclysm:amethyst_crab",
		"cataclysm:ender_golem",
		"cataclysm:aptrgangr",
		"cataclysm:clawdian",
		"cataclysm:kobolediator",
		"cataclysm:wadjet",
		"cataclysm:the_harbinger",
		"cataclysm:ender_guardian",
		"cataclysm:ancient_remnant",
		"cataclysm:maledictus",
		"cataclysm:scylla",
		"cataclysm:ignis",
		"cataclysm:the_leviathan",
		"darkdoppelganger:dark_doppelganger",
		"cataclysm:ignis",
		"spice:warden_boss",
		"spice:soulmob",
		"spice:soul",
		"minecraft:warden",
		"block_factorys_bosses:infernal_dragon",
		"block_factorys_bosses:sandworm",
		"block_factorys_bosses:underworld_knight",
		"block_factorys_bosses:yeti",
		"block_factorys_bosses:poison_area",
		"block_factorys_bosses:fire_area",
		"block_factorys_bosses:ice_spike",
		"block_factorys_bosses:pile_of_bones",
		"block_factorys_bosses:soul_area",
		"adorablehamsterpets:hamster",
		"livingthings:ancient_blaze",
		"hyrule_terrors:keese",
		"cataclysm_spellbooks:summoned_koboldiator",
		"rottencreatures:dead_beard",
		"minecraft:iron_golem",
		"bf_biomes:crab",
		"bf_biomes:bird",
		"bf_biomes:butterfly",
		"bf_biomes:deer",
		"bf_biomes:firefly",
		"bf_biomes:ostrich",
		"bf_biomes:squirrel",
		"guardvillagers:guard",
		"vanillabackport:happy_ghast",
		"",
		"",
		"",
		"",
	]
	death_messages = false
	locked_mobs = [ ]
	can_be_ascendant = [ ]
